config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "dashboard#index"

  resources :transfers, only: :create
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user, inverse_of: :account

  has_many :financial_transactions, dependent: :destroy

  validates :user_id, presence: true
  validates :balance, presence: true, numericality: { greater_than_or_equal_to: 0 }

  delegate :email, to: :user

  scope :available_receivers_for, -> (account) { where.not(id: account) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/credit.rb
class Credit
  include ActiveModel::Model

  attr_accessor\
    :amount,
    :receiver_id

  validates :amount, presence: true
  validates :receiver_id, presence: true

  def receiver
    @receiver ||= Account.find(receiver_id)
  end

  def call
    ActiveRecord::Base.transaction do
      return unless valid?
      receiver.balance += amount
      receiver.financial_transactions.create!(type: 'credit', amount: amount, description: 'Credit by bank')
      receiver.save!
    end
  end
end

app/models/financial_transaction.rb
class FinancialTransaction < ApplicationRecord
  self.inheritance_column = nil

  belongs_to :account

  delegate :email, to: :account, prefix: true
end

app/models/transfer.rb
class Transfer
  include ActiveModel::Model

  attr_accessor\
    :amount,
    :receiver_id,
    :sender_id

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :receiver_id, presence: true
  validates :sender_id, presence: true

  validate :sender_receiver_uniqueness
  validate :sender_positive_balance

  def sender
    @sender ||= Account.find_by(id: sender_id)
  end

  def receiver
    @receiver ||= Account.find_by(id: receiver_id)
  end

  def call
    ActiveRecord::Base.transaction do
      return unless valid?
      sender.balance   -= amount
      receiver.balance += amount

      ref = SecureRandom.hex

      sender.financial_transactions.create!\
        type: 'withdraw',
        amount: amount,
        refferer: ref,
        description: "Transfer to #{receiver.email}"

      receiver.financial_transactions.create!\
        type: 'deposit',
        amount: amount,
        refferer: ref,
        description: "Transfer from #{sender.email}"

      sender.save!
      receiver.save!
    end
  rescue StandardError => err
    errors.add(:sender, :id, message: err.message)
  end

  private

  def sender_positive_balance
    return if (sender&.balance.to_f - amount.to_f) >= 0
    errors.add(:sender, :ammount, message: 'has insufficient amount')
  end

  def sender_receiver_uniqueness
    return unless sender_id == receiver_id
    errors.add(:sender, :id, message: 'can not be equal receiver')
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :rememberable, :validatable

  has_one :account, dependent: :destroy, inverse_of: :user
  has_many :financial_transactions, through: :account, dependent: :destroy

  after_create :create_account, unless: :account

  delegate :balance, to: :account
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  helper_method :current_account

  private

  def current_account
    current_user.account
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @transactions = current_user.financial_transactions
                                .order(created_at: :desc)
                                .decorate
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  def create
    @transfer = Transfer.new(assign_attributes)
    @transfer.call

    if @transfer.errors.messages.empty?
      redirect_to root_path, format: 'js'
    else
      render 'create'
    end
  end

  private

  def assign_attributes
    receiver_id = params.dig(:transfer, :receiver_id)
    amount      = params.dig(:transfer, :amount).to_f
    sender      = current_account

    { sender_id: sender.id, receiver_id: receiver_id, amount: amount }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def available_receivers
    Account.available_receivers_for(current_account)
  end
end

app/views/dashboard/_list.haml
%table.table.transactions-list
  %thead
    %tr
      %th{scope: 'col'}= 'ID'
      %th{scope: 'col'}= 'Date'
      %th{scope: 'col'}= 'Amount'
      %th{scope: 'col'}= 'Ref'
      %th{scope: 'col'}= 'Description'
  %tbody
    - @transactions.each do |transaction|
      %tr
        %td= transaction.id
        %td= transaction.created_at
        %td= transaction.amount
        %td= transaction.refferer
        %td= transaction.description

app/views/dashboard/index.haml
.row
  .col-md-9
    = render 'list'
  .col-md-3
    = current_user.decorate.balance
    %button.btn.btn-primary{"data-target" => '#new-modal', 'data-toggle' => 'modal', type: 'button'}
      Transfer

= render 'shared/modal', title: 'New transfer' do
  = render 'transfers/form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Bankapp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-dark.bg-primary
      = link_to 'Bankapp', root_path, class: 'navbar-brand'
      - if signed_in?
        %span.navbar-brand= current_user.email
        = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-lg active nav-link float-right', role: 'button'

    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"

    .container{style: 'padding: 10px'}
      = yield

app/views/shared/_modal.haml
#new-modal.modal.fade{'aria-hidden' => 'true', 'aria-labelledby' => 'new-modal-label', role: 'dialog', tabindex: '-1'}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#new-modal-label.modal-title= title
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        = yield

app/views/transfers/_errors.haml
.alert.alert-danger
  = pluralize(@transfer.errors.count, 'error')
  prohibited this transfer from being performed:
  %ul
    - @transfer.errors.full_messages.each do |msg|
      %li="* #{msg}"

app/views/transfers/_form.haml
= simple_form_for Transfer.new, url: transfers_path, remote: true do |f|
  #transfer_errors

  = f.input :amount, as: :decimal
  = f.input :receiver_id, collection: available_receivers, label_method: :email

  = f.button :submit, 'Send', class: 'btn btn-primary'

app/views/transfers/create.js.erb
$('#transfer_errors').html("<%= j render 'errors' %>")